name: Tag and Release

on:
  workflow_dispatch

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit_ref }}
      - id: info
        uses: konveyor/get-env-info@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.info.outputs.go_version }}
      - run: which upx
      - run: ls -al "$(which upx)"
